name: account
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.3
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  google_fonts: ^6.2.1
  curved_navigation_bar: ^1.0.6
  path_provider: ^2.1.5
  intl: ^0.17.0
  fl_chart: ^0.69.2
  gap: ^3.0.1
  font_awesome_flutter: ^10.8.0
  expressions: ^0.2.5+2
  sqflite: ^2.4.1
  flutter_launcher_icons: ^0.14.2
  barcode_widget: ^2.0.4

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true


assets:
  - assets/icon/icon.pan